### PR TITLE
Dependency and testing updates

### PR DESCRIPTION
**Pull request by dwbutler**
Hi,

Our team had trouble installing the older FFI 1.5 dependency. So we bumped the FFI dependency and did some cleanup here and there. We also integrated Travis CI to test 1.9.3 and 2.0.0 compatibility. (See the successful build [here](https://travis-ci.org/Spokeo/levenshtein-ffi/builds/7578532)).

Thanks, hope you'll accept this pull request and release a new minor version soon!

### CODE REVIEW

**Comment by ryoqun** [comment]
@dwbutler Thanks for creating this pull request. I'm also stumbled upon this a bit outdated situation.

@dbalatero First of all, thanks for creating this gem! Could you take look at this, please? Thanks :)

**Comment by dbalatero** [comment]
Ah, I think I missed this somehow in my email. I can release a new version soon, although I'd rather not test + push one at this hour! I have a task in my inbox to come back to this, so if not tomorrow, soon.

**Comment by ryoqun** [comment]
Very thanks! I'm looking forward to a release. :D

**Comment by parndt** [comment]
This should still be compatible with #5

**Comment by dbalatero** [comment]
Hey y'all,

A new version (1.1.0) has been pushed. I also enabled Travis CI for this repo. Thanks for the help on this!

Please let me know if this doesn't work for you.

**Pull request merged**
